[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["optimize_for_size"]

[build]
target = "riscv32imac-esp-espidf"

[target.riscv32imac-esp-espidf]
linker = "ldproxy"
runner = "espflash flash -B 921600 -T parts.csv -M"
rustflags = ["--cfg", "espidf_time64"]

[env]
ESP_IDF_VERSION = "v5.3.2"
MCU = "esp32c6"

[profile.release]
opt-level = "z"
codegen-units = 1
panic = "abort"
strip = false
debug = 2
lto = true
